// Compiles the standalone chronicle export stylesheet with the Tailwind CLI
// (`--minify`) and writes it as a TypeScript string module. Committing the
// generated module (rather than emitting at Vite time) keeps `bun test` and
// `tsc` working from a clean checkout, which don't run the Vite pipeline.
//
// Source: src/features/chronicleExport/chronicleExport.css
// Output: src/features/chronicleExport/generated/chronicleExportCss.ts
import { spawnSync } from "node:child_process";
import path from "node:path";
import fs from "fs-extra";

const projectRoot = path.resolve(import.meta.dirname, "..");
const inputFile = path.join(projectRoot, "src/features/chronicleExport/chronicleExport.css");
const relativeOutput = "src/features/chronicleExport/generated/chronicleExportCss.ts";
const outputFile = path.join(projectRoot, relativeOutput);
const tempFile = path.join(projectRoot, "node_modules/.cache/chronicle-export.css");

fs.ensureDirSync(path.dirname(tempFile));
fs.ensureDirSync(path.dirname(outputFile));

const result = spawnSync(
  process.execPath,
  ["x", "@tailwindcss/cli", "-i", inputFile, "-o", tempFile, "--minify"],
  { cwd: projectRoot, stdio: "inherit" },
);
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);

const css = fs.readFileSync(tempFile, "utf-8");
const moduleSource = `// AUTO-GENERATED by scripts/build-chronicle-export-css.ts — do not edit by hand.
// Regenerate with: bun run build:chronicle-css
// Source: src/features/chronicleExport/chronicleExport.css
export const chronicleExportCss: string = ${JSON.stringify(css)};
`;
fs.writeFileSync(outputFile, moduleSource, "utf-8");
console.log(`[chronicle-export-css] wrote ${relativeOutput} (${css.length} bytes)`);
